"""Add Review Model

Revision ID: 6fdc6c66cf7b
Revises: 3178ce77d1d0
Create Date: 2023-12-11 14:31:04.485537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fdc6c66cf7b'
down_revision = '3178ce77d1d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
